name: Check upstream PKGBUILD
on:
  schedule:
    - cron: "0 0 21 * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check upstream PKGBUILD
      run: .github/check-upstream-PKGBUILD
